name: first workflow
on: workflow_dispatch
jobs:
  build:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: build step
        run: echo "build job"
      - name: hi step  
        run: echo "hi"
  deploy:
     runs-on: ubuntu-latest
     steps:
       - name: deploy step
         run: echo "deploy job"
