name: inputs
on: workflow_dispatch
 inputs:
  env:
    description: enter the env
    required: true
    type: choice
    options:
     -dev
     -test
     -prod
    
jobs:
  inputjob:
    runs-on: ubuntu-latest
    steps:
      - name: using input paramenters
        run: echo "environment is ${{inputs.env}}
